//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34014
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coelina.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("smtp.web.de")]
        public string smtpServer {
            get {
                return ((string)(this["smtpServer"]));
            }
            set {
                this["smtpServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string mailUser {
            get {
                return ((string)(this["mailUser"]));
            }
            set {
                this["mailUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string mailPassword {
            get {
                return ((string)(this["mailPassword"]));
            }
            set {
                this["mailPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string bcc {
            get {
                return ((string)(this["bcc"]));
            }
            set {
                this["bcc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[Alias2] [Name] ([Kürzel]), \r\nin Ihrer Rolle als [Alias1] schicke ich Ihnen den f" +
            "olgenden Anhang.")]
        public string body {
            get {
                return ((string)(this["body"]));
            }
            set {
                this["body"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Post für [Name] ([Kürzel])")]
        public string betreff {
            get {
                return ((string)(this["betreff"]));
            }
            set {
                this["betreff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string attachment2 {
            get {
                return ((string)(this["attachment2"]));
            }
            set {
                this["attachment2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string attachment3 {
            get {
                return ((string)(this["attachment3"]));
            }
            set {
                this["attachment3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\")]
        public string aktivesVerzeichnis {
            get {
                return ((string)(this["aktivesVerzeichnis"]));
            }
            set {
                this["aktivesVerzeichnis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LogDatei {
            get {
                return ((string)(this["LogDatei"]));
            }
            set {
                this["LogDatei"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public int smtpPort {
            get {
                return ((int)(this["smtpPort"]));
            }
            set {
                this["smtpPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string absender {
            get {
                return ((string)(this["absender"]));
            }
            set {
                this["absender"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cc {
            get {
                return ((string)(this["cc"]));
            }
            set {
                this["cc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string attachment1 {
            get {
                return ((string)(this["attachment1"]));
            }
            set {
                this["attachment1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PasswordSpeichern {
            get {
                return ((bool)(this["PasswordSpeichern"]));
            }
            set {
                this["PasswordSpeichern"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string neuesteDatei {
            get {
                return ((string)(this["neuesteDatei"]));
            }
            set {
                this["neuesteDatei"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string vollständigerPfadZurDatei {
            get {
                return ((string)(this["vollständigerPfadZurDatei"]));
            }
            set {
                this["vollständigerPfadZurDatei"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool maillogSenden {
            get {
                return ((bool)(this["maillogSenden"]));
            }
            set {
                this["maillogSenden"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool immerNeuesteDateiVorschlagen {
            get {
                return ((bool)(this["immerNeuesteDateiVorschlagen"]));
            }
            set {
                this["immerNeuesteDateiVorschlagen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MaileinstellungenKorrekt {
            get {
                return ((bool)(this["MaileinstellungenKorrekt"]));
            }
            set {
                this["MaileinstellungenKorrekt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SSLEinschalten {
            get {
                return ((bool)(this["SSLEinschalten"]));
            }
            set {
                this["SSLEinschalten"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool mailsAlsHtmlSenden {
            get {
                return ((bool)(this["mailsAlsHtmlSenden"]));
            }
            set {
                this["mailsAlsHtmlSenden"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Kopfzeile der Logdatei.")]
        public string kopfDerLogdatei {
            get {
                return ((string)(this["kopfDerLogdatei"]));
            }
            set {
                this["kopfDerLogdatei"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BodyUndCoZurWiedervorlageSpeichern {
            get {
                return ((bool)(this["BodyUndCoZurWiedervorlageSpeichern"]));
            }
            set {
                this["BodyUndCoZurWiedervorlageSpeichern"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ich_selbst@coelina.de")]
        public string DieseMailIgnorieren {
            get {
                return ((string)(this["DieseMailIgnorieren"]));
            }
            set {
                this["DieseMailIgnorieren"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gesperrt.de")]
        public string DieseDomainIgnorieren {
            get {
                return ((string)(this["DieseDomainIgnorieren"]));
            }
            set {
                this["DieseDomainIgnorieren"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NachVersandDateienLöschen {
            get {
                return ((bool)(this["NachVersandDateienLöschen"]));
            }
            set {
                this["NachVersandDateienLöschen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AliasAktiv {
            get {
                return ((bool)(this["AliasAktiv"]));
            }
            set {
                this["AliasAktiv"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LogSpaltenIndex1 {
            get {
                return ((int)(this["LogSpaltenIndex1"]));
            }
            set {
                this["LogSpaltenIndex1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int LogSpaltenIndex2 {
            get {
                return ((int)(this["LogSpaltenIndex2"]));
            }
            set {
                this["LogSpaltenIndex2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int LogSpaltenIndex3 {
            get {
                return ((int)(this["LogSpaltenIndex3"]));
            }
            set {
                this["LogSpaltenIndex3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int LogSpaltenIndex4 {
            get {
                return ((int)(this["LogSpaltenIndex4"]));
            }
            set {
                this["LogSpaltenIndex4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int LogSpaltenIndex5 {
            get {
                return ((int)(this["LogSpaltenIndex5"]));
            }
            set {
                this["LogSpaltenIndex5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int LogSpaltenIndex6 {
            get {
                return ((int)(this["LogSpaltenIndex6"]));
            }
            set {
                this["LogSpaltenIndex6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CCundBCCinLogDateiSchreiben {
            get {
                return ((bool)(this["CCundBCCinLogDateiSchreiben"]));
            }
            set {
                this["CCundBCCinLogDateiSchreiben"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("coelina")]
        public string LogdateiName {
            get {
                return ((string)(this["LogdateiName"]));
            }
            set {
                this["LogdateiName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("txt")]
        public string LogdateiDateiendung {
            get {
                return ((string)(this["LogdateiDateiendung"]));
            }
            set {
                this["LogdateiDateiendung"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"empfaenger1@coelina.de,MÜL,Peter Müller,Sachbearbeiter,Sehr geehrter Herr,0286190990-99,A1;empfaenger2@coelina.de,MEY,Hans Meyer,Vorstandsvorsitzender,Sehr geehrter Herr,0286190990-88,A2;empfaenger3@coelina.de,JAN,Piet Jansen,Syndikus,Sehr geehrter Herr,0286190990-52,A3;empfaenger5@coelina.de,KL,Dr. Petra Kleining,Abteilungsleiterin,Sehr geehrte Frau,0286190990-11,A4")]
        public string AliasListe {
            get {
                return ((string)(this["AliasListe"]));
            }
            set {
                this["AliasListe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RegExBeschreibung1 {
            get {
                return ((string)(this["RegExBeschreibung1"]));
            }
            set {
                this["RegExBeschreibung1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RegExBeschreibung2 {
            get {
                return ((string)(this["RegExBeschreibung2"]));
            }
            set {
                this["RegExBeschreibung2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RegExBeschreibung3 {
            get {
                return ((string)(this["RegExBeschreibung3"]));
            }
            set {
                this["RegExBeschreibung3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RegExBeschreibung4 {
            get {
                return ((string)(this["RegExBeschreibung4"]));
            }
            set {
                this["RegExBeschreibung4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RegExBeschreibung5 {
            get {
                return ((string)(this["RegExBeschreibung5"]));
            }
            set {
                this["RegExBeschreibung5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@\"IP\"")]
        public string RegExBeschreibung6 {
            get {
                return ((string)(this["RegExBeschreibung6"]));
            }
            set {
                this["RegExBeschreibung6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@\"\\b[A-Z0-9._-]+@[A-Z0-9][A-Z0-9.-]{0,61}[A-Z0-9]\\.[A-Z.]{2,6}\\b\"")]
        public string RegExDefinition1 {
            get {
                return ((string)(this["RegExDefinition1"]));
            }
            set {
                this["RegExDefinition1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RegExDefinition2 {
            get {
                return ((string)(this["RegExDefinition2"]));
            }
            set {
                this["RegExDefinition2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RegExDefinition3 {
            get {
                return ((string)(this["RegExDefinition3"]));
            }
            set {
                this["RegExDefinition3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RegExDefinition4 {
            get {
                return ((string)(this["RegExDefinition4"]));
            }
            set {
                this["RegExDefinition4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RegExDefinition5 {
            get {
                return ((string)(this["RegExDefinition5"]));
            }
            set {
                this["RegExDefinition5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@\"((2[0-4]\\d|25[0-5]|[01]?\\d\\d?)\\.){3}(2[0-4]\\d|25[0-5]|[01]?\\d\\d?)\"")]
        public string RegExDefinition6 {
            get {
                return ((string)(this["RegExDefinition6"]));
            }
            set {
                this["RegExDefinition6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RegExBegrenzer1_1 {
            get {
                return ((string)(this["RegExBegrenzer1_1"]));
            }
            set {
                this["RegExBegrenzer1_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RegExBegrenzer1_2 {
            get {
                return ((string)(this["RegExBegrenzer1_2"]));
            }
            set {
                this["RegExBegrenzer1_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RegExBegrenzer1_3 {
            get {
                return ((string)(this["RegExBegrenzer1_3"]));
            }
            set {
                this["RegExBegrenzer1_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RegExBegrenzer1_4 {
            get {
                return ((string)(this["RegExBegrenzer1_4"]));
            }
            set {
                this["RegExBegrenzer1_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RegExBegrenzer1_5 {
            get {
                return ((string)(this["RegExBegrenzer1_5"]));
            }
            set {
                this["RegExBegrenzer1_5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RegExBegrenzer1_6 {
            get {
                return ((string)(this["RegExBegrenzer1_6"]));
            }
            set {
                this["RegExBegrenzer1_6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RegExBegrenzer2_1 {
            get {
                return ((string)(this["RegExBegrenzer2_1"]));
            }
            set {
                this["RegExBegrenzer2_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RegExBegrenzer2_2 {
            get {
                return ((string)(this["RegExBegrenzer2_2"]));
            }
            set {
                this["RegExBegrenzer2_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RegExBegrenzer2_3 {
            get {
                return ((string)(this["RegExBegrenzer2_3"]));
            }
            set {
                this["RegExBegrenzer2_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RegExBegrenzer2_4 {
            get {
                return ((string)(this["RegExBegrenzer2_4"]));
            }
            set {
                this["RegExBegrenzer2_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RegExBegrenzer2_5 {
            get {
                return ((string)(this["RegExBegrenzer2_5"]));
            }
            set {
                this["RegExBegrenzer2_5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RegExBegrenzer2_6 {
            get {
                return ((string)(this["RegExBegrenzer2_6"]));
            }
            set {
                this["RegExBegrenzer2_6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BlindCopyAn {
            get {
                return ((string)(this["BlindCopyAn"]));
            }
            set {
                this["BlindCopyAn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PasswortSpeichern {
            get {
                return ((bool)(this["PasswortSpeichern"]));
            }
            set {
                this["PasswortSpeichern"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LogErweiternUndNichtLöschen {
            get {
                return ((bool)(this["LogErweiternUndNichtLöschen"]));
            }
            set {
                this["LogErweiternUndNichtLöschen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SortierkriteriumLogdatei {
            get {
                return ((string)(this["SortierkriteriumLogdatei"]));
            }
            set {
                this["SortierkriteriumLogdatei"] = value;
            }
        }
    }
}
